package org.curtinfrc.frc2026.shooter;

import static edu.wpi.first.units.Units.RPM;
import static edu.wpi.first.units.Units.Rotations;
import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.Second;
import static edu.wpi.first.units.Units.Seconds;
import static edu.wpi.first.units.Units.Volts;

import com.revrobotics.RelativeEncoder;
import com.revrobotics.spark.SparkLowLevel.MotorType;
import com.revrobotics.spark.SparkMax;
import edu.wpi.first.math.MathUtil;
import edu.wpi.first.math.controller.PIDController;
import edu.wpi.first.math.controller.SimpleMotorFeedforward;
import edu.wpi.first.math.interpolation.InterpolatingDoubleTreeMap;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.FunctionalCommand;
import edu.wpi.first.wpilibj2.command.SubsystemBase;
import edu.wpi.first.wpilibj2.command.sysid.SysIdRoutine;
import java.util.function.BooleanSupplier;
import java.util.function.DoubleSupplier;
import org.littletonrobotics.junction.Logger;

/** Controls the flywheel and its final feeder roller. */
public class Shooter extends SubsystemBase {
  private static final int FEEDER_MOTOR_ID = 4;
  private static final int FLYWHEEL_MOTOR_ID = 5;

  private static final double FEEDER_STAGE_RPM = 1000.0;
  private static final double FEEDER_SHOOT_RPM = 3000.0;
  private static final double FEEDER_SHOOT_RAMP_SECONDS = 0.08;
  private static final double INTAKE_FLYWHEEL_RPM = 1400.0;
  private static final double TWO_METER_FLYWHEEL_RPM = 1400.0;

  private static final double READY_TOLERANCE_RPM = 50.0;
  private static final double READY_STABLE_SECONDS = 0.10;
  private static final double READY_MAXIMUM_ACCELERATION_RPM_PER_SECOND = 600.0;
  private static final double RECOVERY_DROP_RPM = 100.0;
  private static final double SHOT_EVENT_ARMING_SECONDS = 0.04;
  private static final double MAXIMUM_FEED_SECONDS = 0.20;
  private static final double MINIMUM_SHOT_EVENT_SEPARATION_SECONDS = 0.12;
  private static final double IMPACT_DECELERATION_RPM_PER_SECOND = -2500.0;
  private static final double SUPPORTING_DECELERATION_RPM_PER_SECOND = -800.0;
  private static final double FLYWHEEL_CURRENT_RISE_AMPS = 8.0;
  private static final double FEEDER_CURRENT_RISE_AMPS = 6.0;
  private static final double ACCELERATION_FILTER_TIME_CONSTANT_SECONDS = 0.04;
  private static final double RECOVERY_BOOST_VOLTS = 2.0;
  private static final double SHOT_LOAD_BOOST_VOLTS = 0.75;

  private static final SensorlessShotSequencer.Config SHOT_SEQUENCER_CONFIG =
      new SensorlessShotSequencer.Config(
          READY_TOLERANCE_RPM,
          READY_STABLE_SECONDS,
          READY_MAXIMUM_ACCELERATION_RPM_PER_SECOND,
          RECOVERY_DROP_RPM,
          SHOT_EVENT_ARMING_SECONDS,
          MAXIMUM_FEED_SECONDS,
          MINIMUM_SHOT_EVENT_SEPARATION_SECONDS,
          IMPACT_DECELERATION_RPM_PER_SECOND,
          SUPPORTING_DECELERATION_RPM_PER_SECOND,
          FLYWHEEL_CURRENT_RISE_AMPS,
          FEEDER_CURRENT_RISE_AMPS);

  private static final double SYSID_RAMP_VOLTS_PER_SECOND = 1.0;
  private static final double SYSID_STEP_VOLTS = 6.0;
  private static final double SYSID_TIMEOUT_SECONDS = 6.0;
  private static final double SYSID_STOPPED_TOLERANCE_RPM = 50.0;
  private static final double SYSID_STOP_TIMEOUT_SECONDS = 4.0;
  private static final double SYSID_STOP_SETTLE_SECONDS = 0.25;

  // Flywheel controller units are rotations and seconds so SysId gains can be used directly.
  private static final double FLYWHEEL_KP_VOLTS_PER_RPS = 0.054;
  private static final double FLYWHEEL_KS_VOLTS = 0.26555;
  private static final double FLYWHEEL_KV_VOLTS_PER_RPS = 0.13115;
  private static final double FLYWHEEL_KA_VOLTS_PER_RPS_SQUARED = 0.023168;

  private static final InterpolatingDoubleTreeMap FLYWHEEL_RPM_BY_DISTANCE =
      new InterpolatingDoubleTreeMap();
  private static final InterpolatingDoubleTreeMap FLOOR_LANDING_RPM_BY_DISTANCE =
      new InterpolatingDoubleTreeMap();

  static {
    // Starting points generated by scripts/model_shooter.py. The 2 m point is measured; tune the
    // other points on-field and replace them with observed values.
    FLYWHEEL_RPM_BY_DISTANCE.put(1.00, 1225.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(1.50, 1225.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(2.00, 1400.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(2.50, 1500.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(3.00, 1625.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(3.50, 1775.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(4.00, 1900.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(4.50, 2025.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(5.00, 2150.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(5.50, 2250.0);
    FLYWHEEL_RPM_BY_DISTANCE.put(6.00, 2375.0);

    // Generated with scripts/model_shooter.py physics: 0.60 m release height, 70 degree launch,
    // calibrated RPM-to-exit-speed, drag, and backspin. Tune these floor landing ranges on-field.
    FLOOR_LANDING_RPM_BY_DISTANCE.put(0.50, 510.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(1.00, 783.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(1.50, 995.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(2.00, 1176.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(2.50, 1338.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(3.00, 1488.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(3.50, 1630.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(4.00, 1765.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(4.50, 1896.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(5.00, 2023.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(5.50, 2147.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(6.00, 2270.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(6.50, 2391.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(7.00, 2511.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(7.50, 2631.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(8.00, 2751.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(8.50, 2871.0);
    FLOOR_LANDING_RPM_BY_DISTANCE.put(9.00, 2991.0);
  }

  private final SparkMax feederMotor = new SparkMax(FEEDER_MOTOR_ID, MotorType.kBrushless);
  private final SparkMax flywheelMotor = new SparkMax(FLYWHEEL_MOTOR_ID, MotorType.kBrushless);
  private final RelativeEncoder feederEncoder = feederMotor.getEncoder();
  private final RelativeEncoder flywheelEncoder = flywheelMotor.getEncoder();

  private final SysIdRoutine flywheelSysIdRoutine;

  private final PIDController feederVelocityController = new PIDController(0.0003, 0.0, 0.0);
  private final PIDController flywheelVelocityController =
      new PIDController(FLYWHEEL_KP_VOLTS_PER_RPS, 0.0, 0.0);
  private final SimpleMotorFeedforward feederFeedforward = new SimpleMotorFeedforward(0.15, 0.0019);
  private final SimpleMotorFeedforward flywheelFeedforward =
      new SimpleMotorFeedforward(
          FLYWHEEL_KS_VOLTS, FLYWHEEL_KV_VOLTS_PER_RPS, FLYWHEEL_KA_VOLTS_PER_RPS_SQUARED);

  private double feederTargetRpm;
  private double flywheelTargetRpm;
  private double previousFeederTargetRpm;
  private double previousFlywheelTargetRps;
  private double feederCommandedVolts;
  private double feederShootRampStartedSeconds = Double.NaN;
  private double feederShootRampProgress;
  private double flywheelCommandedVolts;
  private double flywheelRecoveryBoostVolts;
  private double flywheelShotLoadBoostVolts;
  private double distanceMeters = Double.NaN;
  private double lastRecoverySeconds;
  private double recoveryStartedSeconds = Double.NaN;
  private double previousVelocitySampleRpm;
  private double previousVelocitySampleSeconds = Double.NaN;
  private double rawFlywheelAccelerationRpmPerSecond;
  private double filteredFlywheelAccelerationRpmPerSecond;
  private double lastDetectedShotSeconds = Double.NaN;
  private double lastPulseMinimumRpm;
  private double lastPulseMaximumDroopRpm;
  private double lastPulseMaximumFlywheelCurrentAmps;
  private double lastPulseMaximumFeederCurrentAmps;
  private double shotDetectionFlywheelCurrentRiseAmps;
  private double shotDetectionFeederCurrentRiseAmps;
  private int completedFeedPulses;
  private int estimatedShotEvents;
  private boolean atSpeed;
  private boolean feedingShot;
  private String lastShotEventReason = "None";
  private String sequenceState = "Stopped";
  private boolean returningFuelToAllianceSide;

  public Shooter() {
    flywheelSysIdRoutine =
        new SysIdRoutine(
            new SysIdRoutine.Config(
                Volts.of(SYSID_RAMP_VOLTS_PER_SECOND).per(Second),
                Volts.of(SYSID_STEP_VOLTS),
                Seconds.of(SYSID_TIMEOUT_SECONDS),
                state -> Logger.recordOutput("Shooter/SysIdState", state.toString())),
            new SysIdRoutine.Mechanism(
                this::runFlywheelSysIdVoltage, null, this, "ShooterFlywheel"));
  }

  /** Runs the existing intake/staging behavior until the command is cancelled. */
  public Command intake() {
    return runEnd(
            () -> {
              sequenceState = "Intaking";
              setFeederVelocity(-FEEDER_STAGE_RPM);
              setFlywheelVelocity(INTAKE_FLYWHEEL_RPM, false, false);
            },
            this::stopMotors)
        .withName("Intake");
  }

  /** Continuously meters shots while held, waiting for flywheel recovery between feeder pulses. */
  public Command shoot(DoubleSupplier distanceSupplier) {
    return shoot(distanceSupplier, () -> false);
  }

  /** Continuously meters either hub shots or alliance-side floor returns while held. */
  public Command shoot(DoubleSupplier distanceSupplier, BooleanSupplier returnSupplier) {
    return createShootCommand(distanceSupplier, returnSupplier, null, 0)
        .withName("Shoot Continuously");
  }

  /** Meters a requested number of feeder pulses, waiting for recovery between each pulse. */
  public Command shootBurst(DoubleSupplier distanceSupplier, int feedPulses) {
    return shootBurst(distanceSupplier, () -> false, feedPulses);
  }

  /** Meters a requested number of hub or alliance-side return pulses. */
  public Command shootBurst(
      DoubleSupplier distanceSupplier, BooleanSupplier returnSupplier, int feedPulses) {
    if (feedPulses <= 0) {
      throw new IllegalArgumentException("feedPulses must be positive");
    }
    return createShootCommand(distanceSupplier, returnSupplier, null, feedPulses)
        .withName("Shoot " + feedPulses + " Pulse Burst");
  }

  /** Continuously shoots at a fixed speed for temporary Test-mode tuning. */
  public Command testShootAtRpm(double targetRpm) {
    if (targetRpm <= 0.0) {
      throw new IllegalArgumentException("targetRpm must be positive");
    }
    return createShootCommand(null, () -> false, () -> targetRpm, 0)
        .withName("Test Shoot " + Math.round(targetRpm) + " RPM");
  }

  /** Runs a slow voltage ramp for flywheel feedforward characterization. */
  public Command flywheelSysIdQuasistatic(SysIdRoutine.Direction direction) {
    return flywheelSysIdRoutine
        .quasistatic(direction)
        .withName("Flywheel SysId Quasistatic " + directionName(direction));
  }

  /** Runs a voltage step for flywheel acceleration characterization. */
  public Command flywheelSysIdDynamic(SysIdRoutine.Direction direction) {
    return flywheelSysIdRoutine
        .dynamic(direction)
        .withName("Flywheel SysId Dynamic " + directionName(direction));
  }

  /** Runs all four flywheel characterization tests, stopping fully between each test. */
  public Command completeFlywheelSysId() {
    return Commands.sequence(
            flywheelSysIdQuasistatic(SysIdRoutine.Direction.kForward),
            waitForFlywheelToStop(),
            flywheelSysIdQuasistatic(SysIdRoutine.Direction.kReverse),
            waitForFlywheelToStop(),
            flywheelSysIdDynamic(SysIdRoutine.Direction.kForward),
            waitForFlywheelToStop(),
            flywheelSysIdDynamic(SysIdRoutine.Direction.kReverse),
            waitForFlywheelToStop())
        .finallyDo(interrupted -> stopMotors())
        .withName("Complete Flywheel SysId");
  }

  private Command waitForFlywheelToStop() {
    return Commands.waitUntil(
            () -> Math.abs(flywheelEncoder.getVelocity()) <= SYSID_STOPPED_TOLERANCE_RPM)
        .withTimeout(SYSID_STOP_TIMEOUT_SECONDS)
        .andThen(Commands.waitSeconds(SYSID_STOP_SETTLE_SECONDS));
  }

  private static String directionName(SysIdRoutine.Direction direction) {
    return direction == SysIdRoutine.Direction.kForward ? "Forward" : "Reverse";
  }

  private void runFlywheelSysIdVoltage(edu.wpi.first.units.measure.Voltage requestedVoltage) {
    feederMotor.setVoltage(0.0);
    feederTargetRpm = 0.0;
    feederCommandedVolts = 0.0;
    feedingShot = false;

    flywheelTargetRpm = 0.0;
    flywheelRecoveryBoostVolts = 0.0;
    flywheelShotLoadBoostVolts = 0.0;
    flywheelCommandedVolts = requestedVoltage.in(Volts);
    flywheelMotor.setVoltage(flywheelCommandedVolts);
    sequenceState = "SysId";
  }

  private Command createShootCommand(
      DoubleSupplier distanceSupplier,
      BooleanSupplier returnSupplier,
      DoubleSupplier fixedRpmSupplier,
      int requestedPulses) {
    SensorlessShotSequencer sequencer =
        new SensorlessShotSequencer(SHOT_SEQUENCER_CONFIG, requestedPulses);

    return new FunctionalCommand(
        () -> {
          sequencer.reset();
          recoveryStartedSeconds = Double.NaN;
          lastRecoverySeconds = 0.0;
          completedFeedPulses = 0;
          estimatedShotEvents = 0;
          feedingShot = false;
          feederShootRampStartedSeconds = Double.NaN;
          feederShootRampProgress = 0.0;
          lastDetectedShotSeconds = Double.NaN;
          lastPulseMinimumRpm = 0.0;
          lastPulseMaximumDroopRpm = 0.0;
          lastPulseMaximumFlywheelCurrentAmps = 0.0;
          lastPulseMaximumFeederCurrentAmps = 0.0;
          shotDetectionFlywheelCurrentRiseAmps = 0.0;
          shotDetectionFeederCurrentRiseAmps = 0.0;
          lastShotEventReason = "None";
        },
        () -> {
          double nowSeconds = Timer.getFPGATimestamp();
          distanceMeters = distanceSupplier != null ? distanceSupplier.getAsDouble() : Double.NaN;
          returningFuelToAllianceSide = returnSupplier.getAsBoolean();
          double targetRpm =
              fixedRpmSupplier != null
                  ? fixedRpmSupplier.getAsDouble()
                  : returningFuelToAllianceSide
                      ? floorLandingSpeedForDistance(distanceMeters)
                      : flywheelSpeedForDistance(distanceMeters);
          double measuredRpm = flywheelEncoder.getVelocity();
          var shotSample =
              new SensorlessShotSequencer.Sample(
                  measuredRpm,
                  targetRpm,
                  filteredFlywheelAccelerationRpmPerSecond,
                  flywheelMotor.getOutputCurrent(),
                  feederMotor.getOutputCurrent());
          boolean wasFeeding = sequencer.isFeeding();
          boolean shouldFeed = sequencer.update(nowSeconds, shotSample);

          if (!wasFeeding && shouldFeed) {
            feederShootRampStartedSeconds = nowSeconds;
          }

          if (wasFeeding && !shouldFeed) {
            recoveryStartedSeconds = nowSeconds;
          } else if (!wasFeeding && shouldFeed && Double.isFinite(recoveryStartedSeconds)) {
            lastRecoverySeconds = nowSeconds - recoveryStartedSeconds;
            recoveryStartedSeconds = Double.NaN;
          }

          setFlywheelVelocity(targetRpm, !shouldFeed, shouldFeed);
          // The intake roller is the final feeder. It must remain stationary while the flywheel
          // spins up or recovers, otherwise game pieces enter the flywheel before it is ready.
          if (shouldFeed) {
            feederShootRampProgress =
                MathUtil.clamp(
                    (nowSeconds - feederShootRampStartedSeconds) / FEEDER_SHOOT_RAMP_SECONDS,
                    0.0,
                    1.0);
            // Smoothstep has zero slope at both ends, reducing the initial hit on the game piece.
            double smoothRamp =
                feederShootRampProgress
                    * feederShootRampProgress
                    * (3.0 - 2.0 * feederShootRampProgress);
            setFeederVelocity(FEEDER_SHOOT_RPM * smoothRamp);
          } else {
            feederShootRampStartedSeconds = Double.NaN;
            feederShootRampProgress = 0.0;
            setFeederVelocity(0.0);
          }
          feedingShot = shouldFeed;
          completedFeedPulses = sequencer.getCompletedPulses();
          estimatedShotEvents = sequencer.getEstimatedShotEvents();
          lastDetectedShotSeconds = sequencer.getLastDetectedEventSeconds();
          lastPulseMinimumRpm = sequencer.getLastPulseMinimumRpm();
          lastPulseMaximumDroopRpm = sequencer.getLastPulseMaximumDroopRpm();
          lastPulseMaximumFlywheelCurrentAmps = sequencer.getLastPulseMaximumFlywheelCurrentAmps();
          lastPulseMaximumFeederCurrentAmps = sequencer.getLastPulseMaximumFeederCurrentAmps();
          if (shouldFeed || wasFeeding) {
            shotDetectionFlywheelCurrentRiseAmps =
                shotSample.flywheelCurrentAmps() - sequencer.getFlywheelCurrentBaselineAmps();
            shotDetectionFeederCurrentRiseAmps =
                shotSample.feederCurrentAmps() - sequencer.getFeederCurrentBaselineAmps();
          } else {
            shotDetectionFlywheelCurrentRiseAmps = 0.0;
            shotDetectionFeederCurrentRiseAmps = 0.0;
          }
          lastShotEventReason = sequencer.getLastEventReason();
          sequenceState = sequencer.getState();
        },
        interrupted -> stopMotors(),
        sequencer::isFinished,
        this);
  }

  public static double flywheelSpeedForDistance(double distanceMeters) {
    if (!Double.isFinite(distanceMeters)) {
      return TWO_METER_FLYWHEEL_RPM;
    }
    return FLYWHEEL_RPM_BY_DISTANCE.get(distanceMeters);
  }

  public static double floorLandingSpeedForDistance(double distanceMeters) {
    if (!Double.isFinite(distanceMeters)) {
      return TWO_METER_FLYWHEEL_RPM;
    }
    return FLOOR_LANDING_RPM_BY_DISTANCE.get(distanceMeters);
  }

  private void setFeederVelocity(double nextTargetRpm) {
    feederTargetRpm = nextTargetRpm;
    feederCommandedVolts =
        feederVelocityController.calculate(feederEncoder.getVelocity(), nextTargetRpm)
            + feederFeedforward.calculateWithVelocities(previousFeederTargetRpm, nextTargetRpm);
    feederCommandedVolts = MathUtil.clamp(feederCommandedVolts, -12.0, 12.0);
    feederMotor.setVoltage(feederCommandedVolts);
    previousFeederTargetRpm = nextTargetRpm;
  }

  private void setFlywheelVelocity(
      double nextTargetRpm, boolean allowRecoveryBoost, boolean applyShotLoadBoost) {
    flywheelTargetRpm = nextTargetRpm;
    double measuredRpm = flywheelEncoder.getVelocity();
    double measuredRps = rpmToRps(measuredRpm);
    double nextTargetRps = rpmToRps(nextTargetRpm);
    flywheelRecoveryBoostVolts =
        allowRecoveryBoost && measuredRpm < nextTargetRpm - RECOVERY_DROP_RPM
            ? RECOVERY_BOOST_VOLTS
            : 0.0;
    flywheelShotLoadBoostVolts = applyShotLoadBoost ? SHOT_LOAD_BOOST_VOLTS : 0.0;
    flywheelCommandedVolts =
        flywheelVelocityController.calculate(measuredRps, nextTargetRps)
            + flywheelFeedforward.calculateWithVelocities(previousFlywheelTargetRps, nextTargetRps)
            + flywheelRecoveryBoostVolts
            + flywheelShotLoadBoostVolts;
    flywheelCommandedVolts = MathUtil.clamp(flywheelCommandedVolts, -12.0, 12.0);
    flywheelMotor.setVoltage(flywheelCommandedVolts);
    previousFlywheelTargetRps = nextTargetRps;
  }

  private static double rpmToRps(double rpm) {
    return RPM.of(rpm).in(RotationsPerSecond);
  }

  /** Stops both motors and holds them stopped until this command is interrupted. */
  public Command stop() {
    return run(this::stopMotors).withName("Stop Shooter");
  }

  /** Stops the intake and shooter once, allowing a later autonomous event to use the subsystem. */
  public Command stopOnce() {
    return runOnce(this::stopMotors).withName("Stop Shooter Once");
  }

  private void stopMotors() {
    feederMotor.setVoltage(0.0);
    flywheelMotor.setVoltage(0.0);
    feederVelocityController.reset();
    flywheelVelocityController.reset();
    feederTargetRpm = 0.0;
    flywheelTargetRpm = 0.0;
    previousFeederTargetRpm = 0.0;
    previousFlywheelTargetRps = 0.0;
    feederCommandedVolts = 0.0;
    feederShootRampStartedSeconds = Double.NaN;
    feederShootRampProgress = 0.0;
    flywheelCommandedVolts = 0.0;
    flywheelRecoveryBoostVolts = 0.0;
    flywheelShotLoadBoostVolts = 0.0;
    distanceMeters = Double.NaN;
    atSpeed = false;
    feedingShot = false;
    sequenceState = "Stopped";
    returningFuelToAllianceSide = false;
  }

  @Override
  public void periodic() {
    double nowSeconds = Timer.getFPGATimestamp();
    double measuredFlywheelRpm = flywheelEncoder.getVelocity();
    updateFlywheelAcceleration(nowSeconds, measuredFlywheelRpm);
    double measuredFlywheelRps = rpmToRps(measuredFlywheelRpm);
    double flywheelTargetRps = rpmToRps(flywheelTargetRpm);
    atSpeed =
        flywheelTargetRpm > 0.0
            && Math.abs(flywheelTargetRpm - measuredFlywheelRpm) <= READY_TOLERANCE_RPM;
    Logger.recordOutput("Shooter/Flywheel/TargetRPM", flywheelTargetRpm);
    Logger.recordOutput("Shooter/Flywheel/TargetRPS", RotationsPerSecond.of(flywheelTargetRps));
    Logger.recordOutput("Shooter/Flywheel/Position", Rotations.of(flywheelEncoder.getPosition()));
    Logger.recordOutput("Shooter/Flywheel/Velocity", RotationsPerSecond.of(measuredFlywheelRps));
    Logger.recordOutput(
        "Shooter/Flywheel/ErrorRPS",
        RotationsPerSecond.of(flywheelTargetRps - measuredFlywheelRps));
    Logger.recordOutput("Shooter/Flywheel/MeasuredRPM", measuredFlywheelRpm);
    Logger.recordOutput("Shooter/Flywheel/ErrorRPM", flywheelTargetRpm - measuredFlywheelRpm);
    Logger.recordOutput("Shooter/Flywheel/CommandedVolts", flywheelCommandedVolts);
    Logger.recordOutput("Shooter/Flywheel/RecoveryBoostVolts", flywheelRecoveryBoostVolts);
    Logger.recordOutput("Shooter/Flywheel/ShotLoadBoostVolts", flywheelShotLoadBoostVolts);
    Logger.recordOutput(
        "Shooter/Flywheel/ReadyMaximumAccelerationRPMPerSecond",
        READY_MAXIMUM_ACCELERATION_RPM_PER_SECOND);
    Logger.recordOutput(
        "Shooter/Flywheel/AppliedVolts",
        Volts.of(flywheelMotor.getAppliedOutput() * flywheelMotor.getBusVoltage()));
    Logger.recordOutput("Shooter/Flywheel/OutputCurrentAmps", flywheelMotor.getOutputCurrent());
    Logger.recordOutput(
        "Shooter/Flywheel/RawAccelerationRPMPerSecond", rawFlywheelAccelerationRpmPerSecond);
    Logger.recordOutput(
        "Shooter/Flywheel/FilteredAccelerationRPMPerSecond",
        filteredFlywheelAccelerationRpmPerSecond);
    Logger.recordOutput(
        "Shooter/Flywheel/MotorTemperatureCelsius", flywheelMotor.getMotorTemperature());
    Logger.recordOutput("Shooter/Flywheel/ActiveFaultBits", flywheelMotor.getFaults().rawBits);
    Logger.recordOutput("Shooter/Flywheel/ActiveWarningBits", flywheelMotor.getWarnings().rawBits);
    Logger.recordOutput("Shooter/Flywheel/BusVoltage", flywheelMotor.getBusVoltage());
    Logger.recordOutput("Shooter/Feeder/TargetRPM", feederTargetRpm);
    Logger.recordOutput("Shooter/Feeder/MeasuredRPM", feederEncoder.getVelocity());
    Logger.recordOutput("Shooter/Feeder/CommandedVolts", feederCommandedVolts);
    Logger.recordOutput("Shooter/Feeder/ShootRampProgress", feederShootRampProgress);
    Logger.recordOutput("Shooter/Feeder/OutputCurrentAmps", feederMotor.getOutputCurrent());
    Logger.recordOutput(
        "Shooter/Feeder/MotorTemperatureCelsius", feederMotor.getMotorTemperature());
    Logger.recordOutput("Shooter/Feeder/ActiveFaultBits", feederMotor.getFaults().rawBits);
    Logger.recordOutput("Shooter/Feeder/ActiveWarningBits", feederMotor.getWarnings().rawBits);
    Logger.recordOutput("Shooter/Feeder/FeedingShot", feedingShot);
    Logger.recordOutput("Shooter/DistanceMeters", distanceMeters);
    Logger.recordOutput("Shooter/AtSpeed", atSpeed);
    Logger.recordOutput("Shooter/SequenceState", sequenceState);
    Logger.recordOutput("Shooter/ReturningFuelToAllianceSide", returningFuelToAllianceSide);
    Logger.recordOutput("Shooter/CompletedFeedPulses", completedFeedPulses);
    Logger.recordOutput("Shooter/EstimatedShotEvents", estimatedShotEvents);
    Logger.recordOutput("Shooter/LastShotEventReason", lastShotEventReason);
    Logger.recordOutput("Shooter/LastDetectedShotSeconds", lastDetectedShotSeconds);
    Logger.recordOutput("Shooter/LastPulseMinimumRPM", lastPulseMinimumRpm);
    Logger.recordOutput("Shooter/LastPulseMaximumDroopRPM", lastPulseMaximumDroopRpm);
    Logger.recordOutput(
        "Shooter/LastPulseMaximumFlywheelCurrentAmps", lastPulseMaximumFlywheelCurrentAmps);
    Logger.recordOutput(
        "Shooter/LastPulseMaximumFeederCurrentAmps", lastPulseMaximumFeederCurrentAmps);
    Logger.recordOutput(
        "Shooter/ShotDetection/FlywheelCurrentRiseAmps", shotDetectionFlywheelCurrentRiseAmps);
    Logger.recordOutput(
        "Shooter/ShotDetection/FeederCurrentRiseAmps", shotDetectionFeederCurrentRiseAmps);
    Logger.recordOutput(
        "Shooter/ShotDetection/ImpactDecelerationThresholdRPMPerSecond",
        IMPACT_DECELERATION_RPM_PER_SECOND);
    Logger.recordOutput(
        "Shooter/ShotDetection/SupportingDecelerationThresholdRPMPerSecond",
        SUPPORTING_DECELERATION_RPM_PER_SECOND);
    Logger.recordOutput(
        "Shooter/ShotDetection/FlywheelCurrentRiseThresholdAmps", FLYWHEEL_CURRENT_RISE_AMPS);
    Logger.recordOutput(
        "Shooter/ShotDetection/FeederCurrentRiseThresholdAmps", FEEDER_CURRENT_RISE_AMPS);
    Logger.recordOutput("Shooter/LastRecoverySeconds", lastRecoverySeconds);
  }

  private void updateFlywheelAcceleration(double nowSeconds, double measuredRpm) {
    if (Double.isFinite(previousVelocitySampleSeconds)) {
      double samplePeriodSeconds = nowSeconds - previousVelocitySampleSeconds;
      if (samplePeriodSeconds > 0.001 && samplePeriodSeconds < 0.1) {
        rawFlywheelAccelerationRpmPerSecond =
            (measuredRpm - previousVelocitySampleRpm) / samplePeriodSeconds;
        double filterWeight =
            samplePeriodSeconds / (ACCELERATION_FILTER_TIME_CONSTANT_SECONDS + samplePeriodSeconds);
        filteredFlywheelAccelerationRpmPerSecond +=
            filterWeight
                * (rawFlywheelAccelerationRpmPerSecond - filteredFlywheelAccelerationRpmPerSecond);
      }
    }
    previousVelocitySampleRpm = measuredRpm;
    previousVelocitySampleSeconds = nowSeconds;
  }
}
